--------------------------------------------------------
--  File created - Tuesday-November-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BIEN_BAN
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."BIEN_BAN" 
   (	"SO_BIEN_BAN" VARCHAR2(20 BYTE), 
	"MA_LOAI_BB" VARCHAR2(20 BYTE), 
	"CL_DATE" DATE, 
	"FILE_ATTACH" VARCHAR2(200 BYTE), 
	"REASON" VARCHAR2(3000 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"IT_OP" VARCHAR2(20 BYTE), 
	"APPROVED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BORROW_STYLE
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."BORROW_STYLE" 
   (	"BORROW_CODE" VARCHAR2(20 BYTE), 
	"BORROW_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUFFER_STATE
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."BUFFER_STATE" 
   (	"MA_TS" NUMBER, 
	"SO_BB" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMP_STATUS
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."EMP_STATUS" 
   (	"ECODE" VARCHAR2(20 BYTE), 
	"EMP_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HUY_TS
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."HUY_TS" 
   (	"BB_HUY" VARCHAR2(20 BYTE), 
	"MA_TS" NUMBER, 
	"APPROVED" NUMBER(3,0), 
	"IT_OP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOAI_BIEN_BAN
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."LOAI_BIEN_BAN" 
   (	"MA_LOAI" VARCHAR2(20 BYTE), 
	"TEN_LOAI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOAI_TS_CAP1
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."LOAI_TS_CAP1" 
   (	"MA_LOAI" VARCHAR2(20 BYTE), 
	"TEN_LOAI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOAI_TS_CAP2
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."LOAI_TS_CAP2" 
   (	"MA_LOAI" VARCHAR2(20 BYTE), 
	"TEN_LOAI" VARCHAR2(20 BYTE), 
	"PHAN_LOAI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."LOGIN" 
   (	"ID_USER" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"PERMISSION" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LUU_KHO
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."LUU_KHO" 
   (	"MA_TS" NUMBER, 
	"TINH_TRANG" VARCHAR2(100 BYTE), 
	"NGAY_UPDATE" DATE, 
	"SO_BB" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODEL
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."MODEL" 
   (	"MODEL" VARCHAR2(20 BYTE), 
	"TYPE_CODE" NUMBER, 
	"MODEL_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUON_VAT_TU
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."MUON_VAT_TU" 
   (	"SO_BB" VARCHAR2(20 BYTE), 
	"MA_TS" NUMBER, 
	"REASON" VARCHAR2(3000 BYTE), 
	"DUE_DATE" DATE, 
	"QUA_HAN" NUMBER(3,0), 
	"ID_NGUOI_MUON" VARCHAR2(20 BYTE), 
	"NGAY_TRA_THUC" DATE, 
	"APPROVED" NUMBER(3,0), 
	"BORROW_CODE" VARCHAR2(20 BYTE), 
	"IT_OP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NGOAI_KHO
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."NGOAI_KHO" 
   (	"MA_TS" NUMBER, 
	"ID_USER" VARCHAR2(20 BYTE), 
	"LATEST_DAY_OUT" DATE, 
	"SO_BB" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NHAN_TRA_TS
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."NHAN_TRA_TS" 
   (	"SO_BB_NHAN" VARCHAR2(20 BYTE), 
	"MA_TS" NUMBER, 
	"ID_NGUOI_TRA" VARCHAR2(20 BYTE), 
	"MA_TINH_TRANG" VARCHAR2(20 BYTE), 
	"REMARK" VARCHAR2(120 BYTE), 
	"APPROVED" NUMBER(3,0), 
	"IT_OP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NHAP_MOI
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."NHAP_MOI" 
   (	"SO_BB" VARCHAR2(20 BYTE), 
	"MA_TS" NUMBER, 
	"APPROVED" NUMBER(3,0), 
	"IT_OP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NSCBGTS
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."NSCBGTS" 
   (	"MANV" VARCHAR2(20 BYTE), 
	"REMARK" VARCHAR2(2000 BYTE), 
	"BAN_GIAO" VARCHAR2(20 BYTE), 
	"NGAY_UPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORG_NAME
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."ORG_NAME" 
   (	"ORG_CODE" VARCHAR2(20 BYTE), 
	"ORG_NAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERMISSION
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."PERMISSION" 
   (	"PER_ID" VARCHAR2(20 BYTE), 
	"PER_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."STATUS" 
   (	"MA_TINH_TRANG" VARCHAR2(20 BYTE), 
	"TEN_TINH_TRANG" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUA_CHUA
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."SUA_CHUA" 
   (	"BB_SUA" VARCHAR2(20 BYTE), 
	"MA_TS" NUMBER, 
	"VAT_TU_XUAT" NUMBER, 
	"ID_NGUOI_YC" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"NGAY_UPDATE" DATE, 
	"APPROVED" NUMBER(3,0), 
	"IT_OP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAI_SAN
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."TAI_SAN" 
   (	"MA_TS" NUMBER, 
	"TEN_TS" VARCHAR2(20 BYTE), 
	"MA_LOAI_TS_CAP1" VARCHAR2(20 BYTE), 
	"MA_LOAI_TS_CAP2" VARCHAR2(20 BYTE), 
	"SN" VARCHAR2(50 BYTE), 
	"FA_TAG" VARCHAR2(50 BYTE), 
	"IT_TAG" VARCHAR2(50 BYTE), 
	"MODEL" VARCHAR2(50 BYTE), 
	"SPEC" VARCHAR2(100 BYTE), 
	"MA_TINH_TRANG" VARCHAR2(20 BYTE), 
	"UNIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."TB_USER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(200 BYTE), 
	"MAIL" VARCHAR2(2200 BYTE), 
	"DEPT" VARCHAR2(2000 BYTE), 
	"OSP" NUMBER(3,0), 
	"EMP_STATUS" VARCHAR2(20 BYTE), 
	"ORG_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UNIT
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."UNIT" 
   (	"UNIT_ID" NUMBER, 
	"UNIT_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table XUAT_KHO
--------------------------------------------------------

  CREATE TABLE "DOVANAN"."XUAT_KHO" 
   (	"SO_BB_XUAT" VARCHAR2(20 BYTE), 
	"MA_TS" NUMBER, 
	"ID_NGUOI_NHAN" VARCHAR2(20 BYTE), 
	"APPROVED" NUMBER(3,0), 
	"IT_OP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOAI_TS_CAP2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."LOAI_TS_CAP2_PK" ON "DOVANAN"."LOAI_TS_CAP2" ("MA_LOAI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BORROW_STYLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."BORROW_STYLE_PK" ON "DOVANAN"."BORROW_STYLE" ("BORROW_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOAI_TS_CAP1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."LOAI_TS_CAP1_PK" ON "DOVANAN"."LOAI_TS_CAP1" ("MA_LOAI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."UNIT_PK" ON "DOVANAN"."UNIT" ("UNIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMP_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."EMP_STATUS_PK" ON "DOVANAN"."EMP_STATUS" ("ECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERMISSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."PERMISSION_PK" ON "DOVANAN"."PERMISSION" ("PER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAI_SAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."TAI_SAN_PK" ON "DOVANAN"."TAI_SAN" ("MA_TS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOAI_BIEN_BAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."LOAI_BIEN_BAN_PK" ON "DOVANAN"."LOAI_BIEN_BAN" ("MA_LOAI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORG_NAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."ORG_NAME_PK" ON "DOVANAN"."ORG_NAME" ("ORG_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."TB_USER_PK" ON "DOVANAN"."TB_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BIEN_BAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."BIEN_BAN_PK" ON "DOVANAN"."BIEN_BAN" ("SO_BIEN_BAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOVANAN"."STATUS_PK" ON "DOVANAN"."STATUS" ("MA_TINH_TRANG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LOAI_TS_CAP2
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."LOAI_TS_CAP2" ADD CONSTRAINT "LOAI_TS_CAP2_PK" PRIMARY KEY ("MA_LOAI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."LOAI_TS_CAP2" MODIFY ("MA_LOAI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOAI_TS_CAP1
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."LOAI_TS_CAP1" ADD CONSTRAINT "LOAI_TS_CAP1_PK" PRIMARY KEY ("MA_LOAI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."LOAI_TS_CAP1" MODIFY ("MA_LOAI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORG_NAME
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."ORG_NAME" ADD CONSTRAINT "ORG_NAME_PK" PRIMARY KEY ("ORG_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."ORG_NAME" MODIFY ("ORG_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_USER
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."TB_USER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DOVANAN"."TB_USER" ADD CONSTRAINT "TB_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BORROW_STYLE
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."BORROW_STYLE" ADD CONSTRAINT "BORROW_STYLE_PK" PRIMARY KEY ("BORROW_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."BORROW_STYLE" MODIFY ("BORROW_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BIEN_BAN
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."BIEN_BAN" ADD CONSTRAINT "BIEN_BAN_PK" PRIMARY KEY ("SO_BIEN_BAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."BIEN_BAN" MODIFY ("SO_BIEN_BAN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOAI_BIEN_BAN
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."LOAI_BIEN_BAN" ADD CONSTRAINT "LOAI_BIEN_BAN_PK" PRIMARY KEY ("MA_LOAI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."LOAI_BIEN_BAN" MODIFY ("MA_LOAI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP_STATUS
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."EMP_STATUS" ADD CONSTRAINT "EMP_STATUS_PK" PRIMARY KEY ("ECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."EMP_STATUS" MODIFY ("ECODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UNIT
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."UNIT" MODIFY ("UNIT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DOVANAN"."UNIT" ADD CONSTRAINT "UNIT_PK" PRIMARY KEY ("UNIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."LOGIN" MODIFY ("ID_USER" NOT NULL ENABLE);
 
  ALTER TABLE "DOVANAN"."LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DOVANAN"."LOGIN" MODIFY ("PERMISSION" NOT NULL ENABLE);
 
  ALTER TABLE "DOVANAN"."LOGIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERMISSION
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."PERMISSION" ADD CONSTRAINT "PERMISSION_PK" PRIMARY KEY ("PER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."PERMISSION" MODIFY ("PER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAI_SAN
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."TAI_SAN" MODIFY ("MA_TS" NOT NULL ENABLE);
 
  ALTER TABLE "DOVANAN"."TAI_SAN" ADD CONSTRAINT "TAI_SAN_PK" PRIMARY KEY ("MA_TS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS
--------------------------------------------------------

  ALTER TABLE "DOVANAN"."STATUS" ADD CONSTRAINT "STATUS_PK" PRIMARY KEY ("MA_TINH_TRANG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DOVANAN"."STATUS" MODIFY ("MA_TINH_TRANG" NOT NULL ENABLE);
